services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Services:
  Messagehub\ShortMessage\Application\Create\CreateShortMessageHandler:
  Messagehub\ShortMessage\Application\ShortMessageWriter:
    class: Messagehub\ShortMessage\Infrastructure\DbalShortMessageWriter
  Messagehub\ShortMessage\Infrastructure\DbalShortMessageReader:
