services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true


  # Services
  Messagehub\ShortMessage\Application\AddShortMessageHandler:


  Messagehub\Entity\ShortMessageRepository:
  Messagehub\ShortMessage\Presentation\AddFormFactory: