services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Services
  Messagehub\ShortMessage\Presentation\ShortMessage:
  Messagehub\ShortMessage\Application\Create\ShortMessageCreator:
  Messagehub\ShortMessage\Application\Create\CreateShortMessageCommandHandler:
  Messagehub\ShortMessage\Domain\ShortMessageRepository:
    class: Messagehub\ShortMessage\Domain\Infrastructure\ShortMessageRepositoryMySql
