services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Services
  Messagehub\ShortMessage\Application\CreateShortMessageHandler:
  Messagehub\ShortMessage\Application\CreateShortMessageValidator:

  Messagehub\Entity\ShortMessageRepository:
  Messagehub\ShortMessage\Presentation\AddFormFactory: