basic_controllers:
    resource: ../src/Controller/
    type: annotation
api_v1_bundle:
        resource: ../src/ApiV1Bundle/
        type: annotation
kernel:
    resource: ../src/Kernel.php
    type: annotation

